spring:
  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        query.in_clause_parameter_padding: true
        default_batch_fetch_size: 50
        connection.provider_disables_autocommit: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    displaydb:
      writer:
        driver-class-name: org.postgresql.Driver
        auto-commit: false
        connection-timeout: 3000
        max-lifetime: 50000
        pool-name: HikariCP-Writer
      reader:
        driver-class-name: org.postgresql.Driver
        auto-commit: true
        connection-timeout: 3000
        max-lifetime: 50000
        pool-name: HikariCP-Reader

---
spring:
  config.activate.on-profile: local
  datasource:
    jdbc-url: jdbc:h2:mem:studydb;INIT=create domain if not exists oid as blob;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    username: sa
    password:
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true


---
spring:
  config.activate.on-profile: dev
  datasource:
  jpa:
    hibernate.show-sql: true


---
spring:
  config.activate.on-profile: beta
  datasource:
  jpa:
    hibernate.show-sql: true


---
spring:
  config.activate.on-profile: prod
  datasource:
