version: '3'
services:
  mongodb:
    image: mongo:6.0.4
    restart: always
    ports:
      - 27017:27017

#  mongo_seed:
#    image: mongo:6.0.4
#    links:
#      - mongodb
#    volumes:
#      - ./mongo-seed:/mongo-seed
#    command:
#      /mongo-seed/import.sh