version: '3'
services:
  mongodb:
    image: mongo:6.0.4
    restart: always
    ports:
      - 27017:27017
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis_boot
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379

#  mongo_seed:
#    image: mongo:6.0.4
#    links:
#      - mongodb
#    volumes:
#      - ./mongo-seed:/mongo-seed
#    command:
#      /mongo-seed/import.sh